@startuml

hide attributes
hide methods
hide members

'Interfacce utente
interface MainWindow{
}

interface FinestraDiario{
}

interface FinestraPagina{
}

'Classi base
class Applicazione{
}

class GestoreDiario{
}

class GestorePagina{
}

'Strutture dati
class ListaDiari{
}

class InfoDiario{
}

class Diario extends InfoDiario{
}

class InfoPagina{
}

class Pagina extends InfoPagina{
}

'Traduttori e salvataggio dati
class Traduci{
}

class Salva{
}

'Interazioni tra interfacce
MainWindow --> FinestraDiario 
FinestraDiario --> FinestraPagina 

'Interazioni con interfacce
MainWindow --> Applicazione 
FinestraDiario --> GestoreDiario 
FinestraPagina --> GestorePagina 

'Relazioni
Applicazione *-- ListaDiari 
GestoreDiario *-- Diario 
GestorePagina *-- Pagina 

'Relazioni traduzione
Applicazione --> Traduci
GestoreDiario --> Traduci
GestorePagina --> Traduci

'Relazioni traduzione
Applicazione --> Salva
GestoreDiario --> Salva
GestorePagina --> Salva

'Relazioni strutture dati
ListaDiari *-- InfoDiario 
Diario *-- InfoPagina 

@enduml
